export const LAYOUT_PARAMS = {
  navHeight: 50,
  tabHeight: 40,
  sideWidth: 240,
  sideCollapsedWidth: 64,
  sideMenuCollapsedWidth: 48,
  contentPadding: 20,
  footHeight: 50,
  backTopRight: 20,
  backTopBottom: 75,
  backTopVisibilityHeight: 250,
  settingsDrawerWidth: 330,
  settingsButtonRight: 25,
  settingsButtonBottom: 350,
}
