/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ABackTop: typeof import('@arco-design/web-vue')['BackTop']
    ABadge: typeof import('@arco-design/web-vue')['Badge']
    ABreadcrumb: typeof import('@arco-design/web-vue')['Breadcrumb']
    ABreadcrumbItem: typeof import('@arco-design/web-vue')['BreadcrumbItem']
    AButton: typeof import('@arco-design/web-vue')['Button']
    ADrawer: typeof import('@arco-design/web-vue')['Drawer']
    ALayout: typeof import('@arco-design/web-vue')['Layout']
    ALayoutContent: typeof import('@arco-design/web-vue')['LayoutContent']
    ALayoutFooter: typeof import('@arco-design/web-vue')['LayoutFooter']
    ALayoutHeader: typeof import('@arco-design/web-vue')['LayoutHeader']
    AMenu: typeof import('@arco-design/web-vue')['Menu']
    AMenuItem: typeof import('@arco-design/web-vue')['MenuItem']
    APageHeader: typeof import('@arco-design/web-vue')['PageHeader']
    APopover: typeof import('@arco-design/web-vue')['Popover']
    AppProvider: typeof import('./components/AppProvider.vue')['default']
    AResult: typeof import('@arco-design/web-vue')['Result']
    ASpace: typeof import('@arco-design/web-vue')['Space']
    ASubMenu: typeof import('@arco-design/web-vue')['SubMenu']
    ATabPane: typeof import('@arco-design/web-vue')['TabPane']
    ATabs: typeof import('@arco-design/web-vue')['Tabs']
    CommonIcon: typeof import('./components/common/CommonIcon.vue')['default']
    CommonTransition: typeof import('./components/common/CommonTransition.vue')['default']
    Layout: typeof import('./components/layout/Layout.vue')['default']
    LayoutBackTop: typeof import('./components/layout/back-top/LayoutBackTop.vue')['default']
    LayoutBell: typeof import('./components/layout/nav/LayoutBell.vue')['default']
    LayoutFoot: typeof import('./components/layout/foot/LayoutFoot.vue')['default']
    LayoutFullscreen: typeof import('./components/layout/nav/LayoutFullscreen.vue')['default']
    LayoutHorizontal: typeof import('./components/layout/LayoutHorizontal.vue')['default']
    LayoutLogo: typeof import('./components/layout/logo/LayoutLogo.vue')['default']
    LayoutMain: typeof import('./components/layout/main/LayoutMain.vue')['default']
    LayoutMainContent: typeof import('./components/layout/main/LayoutMainContent.vue')['default']
    LayoutMenu: typeof import('./components/layout/menu/LayoutMenu.vue')['default']
    LayoutNav: typeof import('./components/layout/nav/LayoutNav.vue')['default']
    LayoutNavBreadcrumb: typeof import('./components/layout/nav/LayoutNavBreadcrumb.vue')['default']
    LayoutNavDarkToggle: typeof import('./components/layout/nav/LayoutNavDarkToggle.vue')['default']
    LayoutNavDropdown: typeof import('./components/layout/nav/LayoutNavDropdown.vue')['default']
    LayoutNavGithub: typeof import('./components/layout/nav/LayoutNavGithub.vue')['default']
    LayoutPageHeader: typeof import('./components/layout/page-header/LayoutPageHeader.vue')['default']
    LayoutProvider: typeof import('./components/layout/provider/LayoutProvider.vue')['default']
    LayoutResponsivePanel: typeof import('./components/layout/nav/LayoutResponsivePanel.vue')['default']
    LayoutSettings: typeof import('./components/layout/settings/LayoutSettings.vue')['default']
    LayoutSide: typeof import('./components/layout/side/LayoutSide.vue')['default']
    LayoutSmallScreenSide: typeof import('./components/layout/side/LayoutSmallScreenSide.vue')['default']
    LayoutTabs: typeof import('./components/layout/tab/LayoutTabs.vue')['default']
    LayoutVertical: typeof import('./components/layout/LayoutVertical.vue')['default']
    PreloadAnimationPage: typeof import('./components/PreloadAnimationPage.vue')['default']
    PreLoadAnimationPage: typeof import('./components/PreLoadAnimationPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
