/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('@arco-design/web-vue')['Button']
    ALayout: typeof import('@arco-design/web-vue')['Layout']
    ALayoutContent: typeof import('@arco-design/web-vue')['LayoutContent']
    ALayoutFooter: typeof import('@arco-design/web-vue')['LayoutFooter']
    ALayoutHeader: typeof import('@arco-design/web-vue')['LayoutHeader']
    AppProvider: typeof import('./components/AppProvider.vue')['default']
    AResult: typeof import('@arco-design/web-vue')['Result']
    ASpace: typeof import('@arco-design/web-vue')['Space']
    CommonIcon: typeof import('./components/common/CommonIcon.vue')['default']
    CommonTransition: typeof import('./components/common/CommonTransition.vue')['default']
    Layout: typeof import('./components/layout/Layout.vue')['default']
    LayoutBackTop: typeof import('./components/layout/back-top/LayoutBackTop.vue')['default']
    LayoutFoot: typeof import('./components/layout/foot/LayoutFoot.vue')['default']
    LayoutHorizontal: typeof import('./components/layout/LayoutHorizontal.vue')['default']
    LayoutLogo: typeof import('./components/layout/logo/LayoutLogo.vue')['default']
    LayoutMain: typeof import('./components/layout/main/LayoutMain.vue')['default']
    LayoutMainContent: typeof import('./components/layout/main/LayoutMainContent.vue')['default']
    LayoutMenu: typeof import('./components/layout/menu/LayoutMenu.vue')['default']
    LayoutNav: typeof import('./components/layout/nav/LayoutNav.vue')['default']
    LayoutPageHeader: typeof import('./components/layout/page-header/LayoutPageHeader.vue')['default']
    LayoutProvider: typeof import('./components/layout/provider/LayoutProvider.vue')['default']
    LayoutSettings: typeof import('./components/layout/settings/LayoutSettings.vue')['default']
    LayoutSide: typeof import('./components/layout/side/LayoutSide.vue')['default']
    LayoutTabs: typeof import('./components/layout/tab/LayoutTabs.vue')['default']
    LayoutVertical: typeof import('./components/layout/LayoutVertical.vue')['default']
    PreloadAnimationPage: typeof import('./components/PreloadAnimationPage.vue')['default']
    PreLoadAnimationPage: typeof import('./components/PreLoadAnimationPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
